# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01cde81067c576b27717803e65d907c3bec970ae6632f3edf167337c3a64ea130f7c62ced6227402816f3b4d1fe4ee5b8dc46767ef83814f6dd7402b0516e327

test:
  secret_key_base: b09adc87a00347b45549e116d915a652618645ba3332cd6eb07564a6bf0f86a5b7cc8b803eee34fd819ae47370ca384458e427443fece3cc8d680908db46a6d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
